/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "LISTBOX.h"
#include "windows.h"
#include "main.h"
#include "usart.h"
#include "stdlib.h"
#include "string.h"
//#include "stm32f1xx_it.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0        (GUI_ID_USER + 0x03)
#define ID_MULTIEDIT_0        (GUI_ID_USER + 0x04)
#define WM_DOWN               (WM_USER + 0x00) /* 自定义消息 */  
#define WM_clean               (WM_USER + 0x01) /* 自定义消息 */  

uint8_t key0,key1,wk_up; 
int i;
int list,count;
char banduate[10];
char rx_buffer[100]={0};
extern int flag12;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 0, 80, 44, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 0, 46, 240, 273, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hwindows;
  WM_HWIN hListbox;
  WM_HWIN hMultiedit;
  hwindows=pMsg->hWin;
    
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    //hwindows = pMsg->hWin;
    WINDOW_SetBkColor(hwindows, GUI_MAKE_COLOR(0x00FF8000));
    //
    // Initialization of 'Listbox'
    //
    hListbox = WM_GetDialogItem(hwindows, ID_LISTBOX_0);
    LISTBOX_AddString(hListbox, "9600");
    LISTBOX_AddString(hListbox, "19200");
    LISTBOX_AddString(hListbox, "115200");
    LISTBOX_SetMulti (hListbox,1);
  
    hMultiedit = WM_GetDialogItem(hwindows, ID_MULTIEDIT_0);
    MULTIEDIT_SetAutoScrollV(hMultiedit,1);
    MULTIEDIT_SetWrapWord(hMultiedit);
    //MULTIEDIT_SetTextAlign(hMultiedit,GUI_TA_HCENTER);
    MULTIEDIT_SetFont(hMultiedit, &GUI_Font8x16);
    //MULTIEDIT_SetText(hMultiedit,"123456");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
  
    break;
  
  case WM_DOWN:
      hListbox = WM_GetDialogItem(hwindows, ID_LISTBOX_0);
      hMultiedit = WM_GetDialogItem(hwindows, ID_MULTIEDIT_0);
      GUI_Delay(200);
      if(i>=0&&i<3){    
          ++i;          
          LISTBOX_SetItemSel(hListbox,i-1,0);  
          LISTBOX_SetItemSel(hListbox,i,1);
          
      }
      else {
          LISTBOX_SetItemSel(hListbox,2,0);
          LISTBOX_SetItemSel(hListbox,0,1);
          i=0;
          
      }  
       LISTBOX_GetItemText(hListbox,i-1,banduate,sizeof(banduate)); 
       //MULTIEDIT_SetText(hMultiedit,banduate);
       //GUI_Delay(100);

      //printf("%s\n",banduate);
    break;
      
  case WM_clean:
        hMultiedit = WM_GetDialogItem(hwindows, ID_MULTIEDIT_0);
        MULTIEDIT_SetText(hMultiedit,"");
        GUI_Delay(10);
    break;
  
  case WM_SEND:
      hMultiedit = WM_GetDialogItem(hwindows, ID_MULTIEDIT_0);
      MULTIEDIT_AddText(hMultiedit,rx_buffer);
      //MULTIEDIT_AddText(hMultiedit,"\n");
      count++;     
      memset(rx_buffer,0,100);
  if(count>=30) {
      MULTIEDIT_SetText(hMultiedit,"");
      count=0;
  }
  GUI_Delay(10);
      break;
  
  default:

//    GUI_Delay(100);
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
 
    //GUI_Delay(100);
  return hWin;
}

// USER START (Optionally insert additional public code)
void window(void const * argument){
    WM_HWIN msg;
    GUI_Init();
    msg=CreateWindow();
    GUI_Delay(200);
    for(;;){
        if(key1==1){
            list=atoi(banduate);
            MX_USART1_UART_Init(list);
            HAL_Delay(500);
        }   
      
         
        if(key0==1)  WM_SendMessageNoPara(WM_GetClientWindow(msg), WM_DOWN);
        if(wk_up==1)  WM_SendMessageNoPara(WM_GetClientWindow(msg), WM_clean);
//        printf("%s\n",banduate);
        if(flag12==1){
            WM_SendMessageNoPara(WM_GetClientWindow(msg), WM_SEND);
            flag12=0;
        }
       
       
    }
    

}



// USER END

/*************************** End of file ****************************/
